version: "3"
services:

    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: prasannakumarr06/portoimage:web-1.0
        ports:
            - "8001:80"
        volumes:
            - ./Web:/var/www/html/
            - ./.htaccess:/var/www/html/.htaccess
        links:
            - db
        networks:
            - default

    db:
        build: 
            context: .
            dockerfile: db.dockerfile
        image: prasannakumarr06/portoimage:mysql-8.0.16
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_DATABASE: portfolio
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        build: 
            context: .
            dockerfile: phpmyadmin.dockerfile
        image: prasannakumarr06/portoimage:phpmyadmin-4.8
        links:
            - db:db
        ports:
            - 9000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test

volumes:
    persistent: