name: Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Container
        uses: docker://prasannakumarr06/portoimage:latest
        with:
          args: -d -p 8080:80
        
